---
# This is the name of the workflow, visible on GitHub UI
name: Check Spelling

on:
  push:
    branches-ignore: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Spelling
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
